CREATE DATABASE IF NOT EXISTS cruddb;
USE cruddb;
CREATE TABLE IF NOT EXISTS alunos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  idade INT NOT NULL,
  curso VARCHAR(100) NOT NULL
);
